"""worker_notification

Revision ID: 196ecbf4bf59
Revises: 42c1024d0d23
Create Date: 2024-04-15 16:25:26.763276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '196ecbf4bf59'
down_revision: Union[str, None] = '42c1024d0d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('WorkerNotification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('resume_offer_id', sa.BigInteger(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['resume_offer_id'], ['ResumeOffer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WorkerNotification')
    # ### end Alembic commands ###
