"""worker_notification_table_update

Revision ID: 6f664a0c526d
Revises: 196ecbf4bf59
Create Date: 2024-04-15 16:47:36.579069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f664a0c526d'
down_revision: Union[str, None] = '196ecbf4bf59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WorkerNotification', sa.Column('is_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WorkerNotification', 'is_checked')
    # ### end Alembic commands ###
