"""feat: ResumeOffer

Revision ID: 8642a894bbfc
Revises: cd8be9ec4907
Create Date: 2024-04-14 22:30:40.936121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8642a894bbfc'
down_revision: Union[str, None] = 'cd8be9ec4907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
