"""feat: all_tables

Revision ID: cd8be9ec4907
Revises: 73fee6c2b6f2
Create Date: 2024-04-14 15:31:34.019027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8be9ec4907'
down_revision: Union[str, None] = '73fee6c2b6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DisabilityType',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Organization',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Profession',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Offer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('profession_id', sa.BigInteger(), nullable=True),
    sa.Column('disability_id', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['disability_id'], ['DisabilityType.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['Profession.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Resume',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.Column('profession_id', sa.BigInteger(), nullable=True),
    sa.Column('disability_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['disability_id'], ['DisabilityType.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['Profession.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Experience',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('is_work_now', sa.Boolean(), nullable=True),
    sa.Column('resume_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['Resume.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('User', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'organization_id')
    op.drop_table('Experience')
    op.drop_table('Resume')
    op.drop_table('Offer')
    op.drop_table('Profession')
    op.drop_table('Organization')
    op.drop_table('DisabilityType')
    # ### end Alembic commands ###
